# docker-compose.yml
version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8080"
    depends_on:
      - vehicle-service
      - reservation-service
      - user-service
    networks:
      - gdldv-network

  vehicle-service:
    build: ./vehicle-service
    ports:
      - "8001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/gdldv_vehicle_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - gdldv-network

  reservation-service:
    build: ./reservation-service
    ports:
      - "8002:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/gdldv_reservation_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - gdldv-network

  user-service:
    build: ./user-service
    ports:
      - "8003:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/gdldv_user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - gdldv-network

networks:
  gdldv-network:
    driver: bridge